//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPIntegrationWebService.ERPIntegrationWSReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brokerapplication.org/", ConfigurationName="ERPIntegrationWSReference.ERPIntegrationWSSoap")]
    public interface ERPIntegrationWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/InsertEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertEmployee(string no, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateEmployee(string no, string name, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/DeleteEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteEmployee(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/SearchEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SearchEmployee(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetEmployeeAndMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEmployeeAndMetaData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetEmployeeAndRelatives", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEmployeeAndRelatives();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetSickEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSickEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetMostSickEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMostSickEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetAllKeys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetAllIndexes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllIndexes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetAllConstraints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllConstraints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetAllTables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetAllTables2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllTables2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetColumnsEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetColumnsEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetColumnsEmployee2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetColumnsEmployee2();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERPIntegrationWSSoapChannel : ERPIntegrationWebService.ERPIntegrationWSReference.ERPIntegrationWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPIntegrationWSSoapClient : System.ServiceModel.ClientBase<ERPIntegrationWebService.ERPIntegrationWSReference.ERPIntegrationWSSoap>, ERPIntegrationWebService.ERPIntegrationWSReference.ERPIntegrationWSSoap {
        
        public ERPIntegrationWSSoapClient() {
        }
        
        public ERPIntegrationWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERPIntegrationWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPIntegrationWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPIntegrationWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertEmployee(string no, string name) {
            base.Channel.InsertEmployee(no, name);
        }
        
        public void UpdateEmployee(string no, string name, string lastName) {
            base.Channel.UpdateEmployee(no, name, lastName);
        }
        
        public void DeleteEmployee(string no) {
            base.Channel.DeleteEmployee(no);
        }
        
        public void SearchEmployee(string searchString) {
            base.Channel.SearchEmployee(searchString);
        }
        
        public System.Data.DataSet GetEmployeeAndMetaData() {
            return base.Channel.GetEmployeeAndMetaData();
        }
        
        public System.Data.DataSet GetEmployeeAndRelatives() {
            return base.Channel.GetEmployeeAndRelatives();
        }
        
        public System.Data.DataSet GetSickEmployee() {
            return base.Channel.GetSickEmployee();
        }
        
        public System.Data.DataSet GetMostSickEmployee() {
            return base.Channel.GetMostSickEmployee();
        }
        
        public System.Data.DataSet GetAllKeys() {
            return base.Channel.GetAllKeys();
        }
        
        public System.Data.DataSet GetAllIndexes() {
            return base.Channel.GetAllIndexes();
        }
        
        public System.Data.DataSet GetAllConstraints() {
            return base.Channel.GetAllConstraints();
        }
        
        public System.Data.DataSet GetAllTables() {
            return base.Channel.GetAllTables();
        }
        
        public System.Data.DataSet GetAllTables2() {
            return base.Channel.GetAllTables2();
        }
        
        public System.Data.DataSet GetColumnsEmployee() {
            return base.Channel.GetColumnsEmployee();
        }
        
        public System.Data.DataSet GetColumnsEmployee2() {
            return base.Channel.GetColumnsEmployee2();
        }
    }
}
