//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPIntegrationWebService.ERPIntegrationWSReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brokerapplication.org/", ConfigurationName="ERPIntegrationWSReference.ERPIntegrationWSSoap")]
    public interface ERPIntegrationWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/InsertEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/DeleteEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetAllEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllEmployees();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERPIntegrationWSSoapChannel : ERPIntegrationWebService.ERPIntegrationWSReference.ERPIntegrationWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPIntegrationWSSoapClient : System.ServiceModel.ClientBase<ERPIntegrationWebService.ERPIntegrationWSReference.ERPIntegrationWSSoap>, ERPIntegrationWebService.ERPIntegrationWSReference.ERPIntegrationWSSoap {
        
        public ERPIntegrationWSSoapClient() {
        }
        
        public ERPIntegrationWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERPIntegrationWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPIntegrationWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPIntegrationWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertEmployee() {
            base.Channel.InsertEmployee();
        }
        
        public void UpdateEmployee() {
            base.Channel.UpdateEmployee();
        }
        
        public void DeleteEmployee() {
            base.Channel.DeleteEmployee();
        }
        
        public System.Data.DataSet GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
    }
}
